Import the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#importing the data
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
101100,67724,-1.616309,0.301528,2.576196,-1.383581,-1.957517,0.324467,-1.291105,1.045400,0.644268,...,0.147246,0.738228,-0.235067,0.404765,0.493298,-0.084823,0.435332,0.184834,2.00,0.0
101101,67724,1.360267,-0.436744,0.489853,0.090982,-0.815665,-0.224158,-0.495517,-0.144244,-0.560410,...,-0.487255,-0.639351,-0.067000,-0.068650,0.544523,0.439444,0.018577,0.015192,11.50,0.0
101102,67725,-0.408663,1.081556,1.574662,-0.036676,-0.040507,-0.887630,0.732968,-0.088876,-0.454404,...,-0.224136,-0.562357,-0.028645,0.377003,-0.181515,0.069876,0.268195,0.121709,2.28,0.0
101103,67725,-1.495992,0.195264,1.110646,-0.355794,0.007096,-0.284450,0.158197,0.493381,-0.058127,...,0.246418,0.475835,-0.090874,-0.378187,0.183416,0.488217,0.180731,0.027739,103.00,0.0
101104,67726,-0.736580,-0.520894,2.714887,-1.559758,-0.795662,1.006060,-0.907237,0.443974,0.407728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101105 entries, 0 to 101104
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    101105 non-null  int64
 1   V1      101105 non-null  float64
 2   V2      101105 non-null  float64
 3   V3      101105 non-null  float64
 4   V4      101105 non-null  float64
 5   V5      101105 non-null  float64
 6   V6      101105 non-null  float64
 7   V7      101105 non-null  float64
 8   V8      101105 non-null  float64
 9   V9      101105 non-null  float64
 10  V10     101105 non-null  float64
 11  V11     101105 non-null  float64
 12  V12     101105 non-null  float64
 13  V13     101105 non-null  float64
 14  V14     101105 non-null  float64
 15  V15     101105 non-null  float64
 16  V16     101105 non-null  float64
 17  V17     101105 non-null  float64
 18  V18     101105 non-null  float64
 19  V19     101105 non-null  float64
 20  V20     101105 non-null  float64
 21  V21     101104 non-null  float64
 22  V22     101104 non-null  float64
 23  V23     101104 non-null  float64
 24  V24     101104 non-null  float64
 25  V25     101104 non-null  float64
 26  V26     101104 non-null  float64
 27  V27     101104 non-null  float64
 28  V28     101104 non-null  float64
 29  Amount  101104 non-null  float64
 30  Class   101104 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 23.9 MB

In [6]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64