<a href="https://colab.research.google.com/github/Shreya1998-35/amex-data-quality-pipeline/blob/data_quality_pipeline_using_ML/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Dependencies

In [57]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [15]:
#importing the data
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [16]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [17]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [18]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [19]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [20]:
credit_card_data = credit_card_data.dropna()

In [21]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [22]:
#Distribution of legit and fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This Data is unbalanced......... 0--> Normal Transaction 1--> Fraudulent Transaction

In [23]:
#separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [24]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [25]:
#statistical measures
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [26]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [27]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under-sampling

Build a sample dataset containing similar distribution of normal and fraud transactions

no. of fraudulent transaction--> 492

In [28]:
legit_sample = legit.sample(n=492)

In [29]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [30]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
203215,134715.0,1.159500,-2.315304,-1.441802,-1.526156,-0.607909,0.985794,-0.501015,0.388913,2.133511,...,0.531840,0.868513,-0.222966,-1.603811,-0.477395,-0.079581,-0.010128,-0.003335,409.23,0
95614,65392.0,1.042632,-0.251363,1.232422,1.609592,-0.708011,0.908655,-0.689215,0.473220,1.100019,...,-0.374127,-0.664155,0.083130,0.005750,0.373185,-0.524282,0.083430,0.016474,7.48,0
87759,61824.0,1.158670,-0.361984,0.393904,-0.739891,-0.665560,-0.337005,-0.281478,0.088789,1.388252,...,0.051506,0.491600,-0.131102,0.266941,0.731795,-0.585111,0.078889,0.008951,9.95,0
206856,136404.0,1.989706,0.198982,-3.645749,0.468984,3.232016,3.062859,0.104829,0.660752,-0.015950,...,-0.032907,-0.003622,-0.003726,0.579304,0.507332,-0.472361,0.017295,-0.032938,20.51,0
33462,37243.0,1.080517,0.220454,0.279842,1.205073,-0.107207,-0.528531,0.308109,-0.080727,-0.148308,...,-0.412989,-1.363082,0.212377,-0.021314,0.139995,-0.813523,0.013530,0.035100,61.65,0

In [31]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [32]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [34]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,99919.991870,-0.176178,-0.178748,-0.090205,0.007936,0.091440,0.004289,0.082993,-0.018520,-0.031236,...,0.020596,0.037127,0.074019,-0.031865,0.025387,0.031945,-0.016275,0.034551,-0.010882,112.492947
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features and Targets

In [35]:
x= new_dataset.drop(columns='Class', axis=1)
y= new_dataset['Class']

In [36]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
203215  134715.0  1.159500 -2.315304 -1.441802 -1.526156 -0.607909  0.985794
95614    65392.0  1.042632 -0.251363  1.232422  1.609592 -0.708011  0.908655
87759    61824.0  1.158670 -0.361984  0.393904 -0.739891 -0.665560 -0.337005
206856  136404.0  1.989706  0.198982 -3.645749  0.468984  3.232016  3.062859
33462    37243.0  1.080517  0.220454  0.279842  1.205073 -0.107207 -0.528531
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
203215 -0.501015  0.388913  2.133511  ...  0.472266  0.531840  0.868513
95614  -0.689215  0.473220  1.100019  ... -0.249823 -0.374127 -0.664155
87759  -0.281478  0.088789  1.388252  ... -0.161062  0.051506  0.491600
206856  0.104829  0.660752 -0.015950  ... -0.147455 -0.032907 -0.003622
33462   0.308109 -0.080727 -0.148308  ... -0.087162 -0.412989 -1.363082
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
203215 -0.222966 -1.603811 -0.477395 -0.079581 -0.010128 -0.003335  409.23
95614   0.083130  0.005750  0.373185 -0.524282  0.083430  0.016474    7.48
87759  -0.131102  0.266941  0.731795 -0.585111  0.078889  0.008951    9.95
206856 -0.003726  0.579304  0.507332 -0.472361  0.017295 -0.032938   20.51
33462   0.212377 -0.021314  0.139995 -0.813523  0.013530  0.035100   61.65
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [37]:
print(y)

203215    0
95614     0
87759     0
206856    0
33462     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into training and testing data

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

### Data Standardization

Standardizing the data is crucial for many machine learning algorithms, including Logistic Regression, as it ensures that all features contribute equally to the distance calculation. This helps the optimization algorithm converge more efficiently.

In [63]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [64]:
print(x_train)

[[-0.45794673  0.30419226 -0.43917499 ...  0.03810198 -0.32555859
   1.70616058]
 [ 1.10038802  0.74788975 -0.57998955 ... -0.0585357  -0.2114528
  -0.04956763]
 [ 0.60554911  0.8428566  -0.80527404 ... -0.17174475 -0.24798825
  -0.03435857]
 ...
 [ 1.09721151  0.07828573  0.49524389 ...  0.36102639 -0.1745578
  -0.43663638]
 [-0.99524841 -2.2773003   1.59954446 ... -1.36962791 -1.51798904
  -0.30714429]
 [-0.599988    0.58448513 -0.78476386 ... -0.10602358  0.03185776
   0.50014819]]

In [65]:
print(x.shape, x_train.shape, x_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

Logistic Regression

In [67]:
model = LogisticRegression(max_iter=1000)

In [68]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

Model Evaluation----------Accuracy Score

In [69]:
#Accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [70]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9504447268106735

In [71]:
#accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [72]:
print('Accuracy on Training data : ', test_data_accuracy)

Accuracy on Training data :  0.9238578680203046